### ISSUE TITLE
OpenAPITestHelper loggolás kikapcsolási lehetősége

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/roaster#14]
Ha nagy az /openapi json válasza, a teszt elszáll.
OpenAPITestHelper -ben kéne olyan lehetőség hogy ki lehessen kapcsolni a loggolást.

**Comment by rombow** [comment]
log().all() elkerulese nem segit?

**Comment by speter555** [comment]
Maga az OpenAPITestHelper van használva, aminek a használatakor nincs lehetőség ennek a kikapcsolására.
Erre az osztályra gondolok:
https://github.com/i-Cell-Mobilsoft-Open-Source/roaster/blob/master/roaster-restassured/src/main/java/hu/icellmobilsoft/roaster/restassured/helper/OpenAPITestHelper.java
És azon belül a testOpenAPI metódus hívására.

Csak hogy ne kelljen projektben duplikálni, azért gondoltam hogy felveszem ezt az issue-t.

**Comment by tamkarcsi** [comment]
A fenti igény mellett szükséges a private static final String EXPECTED_OPENAPI_VERSION = "3.0.1" konstans módosítása is a OpenAPITestHelper-ben 3.0.3-asra. Mivel ez minimális módosítás külön issue-t nem nyitottam rá.

**Comment by speter555** [comment]
> A fenti igény mellett szükséges a private static final String EXPECTED_OPENAPI_VERSION = "3.0.1" konstans módosítása is a OpenAPITestHelper-ben 3.0.3-asra. Mivel ez minimális módosítás külön issue-t nem nyitottam rá.

Szerintem maga a teszt sajnos rossz, mert van olyan lehetőség ahol a roastert használják és 3.0.1 az értéke, van ahol meg már 3.0.3 lehet, ez nem roaster függő dolog, és így a vizsgálandó rész nem mindig lesz igaz. Esetleg csak a meglétét vizsgálva lehet általánosabb megoldást tudnánk adni arra hogy működik az openapi végpont.

**Comment by speter555** [comment]
Sajnos maga a restassured nem ad jó megoldás a probléma megoldására. A meglátásom az hogy sajnos ez a lehetőség jobb ha projekt specifikusan van megvalósítva. @rombow mit gondolsz erről?
