### ISSUE TITLE
FileUtil kiegészítése InputStream response-okkal

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/roaster#73]
FileUtil jelenleg csak String-et ad vissza a fájlt felolvasva. Jó lenne egy olyan metódus is hozzá, ami InputStream-et ad vissza.

**Comment by martin-nagy** [comment]
Mivel lenne ez jobb, mint a java által adott metódusok?
- `InputStream is = Files.newInputStream(path);`
- `InputStream is = ClassLoader.getSystemResourceAsStream(fileName);`

**Comment by speter555** [comment]
Ezek a dolgok és hibakezelésük jobb lenne ha bekerülne a Utilba, mivel nem csak fejlesztők használják a roastert, ezért nekik egyszerűbb lenne az életük, pl a két változat közül egy tesztelő melyiket használja és miért (nem feltétlen tudja).
