### ISSUE TITLE
Redis streamek teszteléséhez modul

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/roaster#82]
Szükséges lenne a coffee által meghatározott redis streamek meghajtásához olyan unit tesztekre amik ezekre a streamekre tudnak üzeneteket pakolni.

**Comment by rombow** [comment]
Leccives ird bele miert lett lezarva

**Comment by speter555** [comment]
Megoldható a felmerülő kérdés a hu.icellmobilsoft.coffee.module.redisstream.common.RedisStreamHandler segítségével .
